ENH: Modernize package setup (#56)
* ENH: Modernize package setup

Modernize packate setup:
- Adopt PEP621 to store project metadata in `pyproject.toml`. Remove the
  `setup.py` file.
- Adopt PEP518 to specify the build system requirements for the
  package.
- Adopt PEP631 to specify the package dependencies in the
  `pyproject.toml` file, and remove the `requirements,txt`.
- Transition to `setuptools_scm` dynamic versioning system.

Change the GHA package test workflow file accordingly.

Add the `_version.py` file to the `.gitignore` file list.

Documentation:
https://peps.python.org/pep-0621/
https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec
https://peps.python.org/pep-0518/
https://peps.python.org/pep-0631/
https://setuptools.pypa.io/en/latest/index.html
https://setuptools-scm.readthedocs.io/en/latest/

* ENH: Require a more recent version of `NumPy`

Require a more recent version of `NumPy`: require any version greater or
equal to 1.19.5 but lower than 2.0.0. `NumPy` 1.19.5 was the first
release supporting Python 3.9.

Fixes:
```
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

raised for example at:
https://github.com/demianw/tract_querier/actions/runs/12145326696/job/33866697673#step:5:806