BUG: Rename scripts: do not use package names to name scripts
Rename scripts: do not use package names to name scripts to avoid
clashes.

If a script has the same name as the package, importing the package or
its submodules within the script may result in Python trying to import
the script itself.

Fixes:
```
Traceback (most recent call last):
  File "/snap/pycharm-professional/443/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/443/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jhlegarreta/src/tract_querier/scripts/tract_querier.py", line 286, in <module>
    main()
  File "/home/jhlegarreta/src/tract_querier/scripts/tract_querier.py", line 94, in main
    if os.path.exists(tract_querier.default_queries_folder):
AttributeError: module 'tract_querier' has no attribute 'default_queries_folder'
```

raised locally when debugging `tract_querier.py`.