ENH: Test the CLI scripts
Test the CLI scripts:
- Adapt and transfer the contents of the `test_scripts.py` test script
  to a more modern and compact approach that uses the `pytest`
  `pytest-console-script` plugin and that does not require fiddling
  with the location of the files. This allows to test that the CLI
  scripts are installed appropriately/called using the names defined in
  the `pyproject.toml` `project.scripts` section.
- Split the tests into two different files following the scripts being
  tested: `tract_math` and `tract_querier`.
- Remove the `test_scripts.py` file.

Add the `pytest-console-script` dependency so that the scripts can be
called when executing `pytest`.

Convert the `output.values()` ordered dictionary values to a list prior
to slicing in `decorator.py`. Fixes:
```
"/src/tract_querier/scripts/cli_tract_math.py",
 line 109, in main\n    operations[args.operation]
(\n  File "/src/tract_querier/tract_querier/tract_math/decorator.py",
 line 148, in wrapper\n    process_output(func(*option_and_args))\n
  File "/src/tract_querier/tract_querier/tract_math/decorator.py",
 line 199, in process_output\n
    first_value = output.values()[0]\n
TypeError: \'odict_values\' object is not subscriptable\n')
```

raised locally when running the script tests.