ENH: Move test files to OSF
Move test files to OSF and refactor the `datasets.py` module:
- Use the new URLs of the test files stored in OSF.
- Add the `b` prefix to the MD5 hashes of the files to match the binary
  string returned by the hash computation method.
- Do not try to encode the byte object with the file contents: some of
  the test files are binary files, and can only be read in binary
  format; trying to read them in text mode raises a `UnicodeDecodeError`
  error when calling `encode('utf-8')` on them, and calling
  `encode('utf-8')` on the bytes read raises a `AttributeError: 'bytes'
  object has no attribute 'encode'` error. Thus, read them in binary
  mode and compute the hash on the returned binary data without trying
  to encode them. Reading the files using chunks is not implemented as
  the files are not that large.
- Remove the unnecessary dependency on `unittest`.