BUG: Add the `py` extension to the script filenames
Rename scripts so that their `main` method can be effectively imported
when installing them as Python scripts that can be effectively called
from the command line: add the `py` extension to the script filenames.

Fixes:
```
Traceback (most recent call last):
  File ".virtualenvs/tract_querier/bin/tract_querier", line 5, in <module>
    from scripts.tract_querier import main
ModuleNotFoundError: No module named 'scripts.tract_querier'
Traceback (most recent call last):
  File ".virtualenvs/tract_querier/bin/tract_querier", line 5, in <module>
    from scripts.tract_querier import main
ModuleNotFoundError: No module named 'scripts.tract_querier'
```

raised locally when executing:
```
tract_querier -t "${tractogram_fname}" -a "${wmparc_fname}" -q "${query_fname}" -o "${out_fname}"
```

using some local data.