ENH: Remove testing with coverage in GHA workflow file
Remove testing with coverage in GHA workflow file.

`nose` is deprecated and when using the coverage option results in:
```
TypeError: '<' not supported between instances of 'module' and 'module'
```