BUG: Provide a class name to the `Sphinx` lexer
Provide a class name to the `Sphinx` lexer: the `add_lexer` method does
not accept lexer instances as an argument since version 4.0.

Fixes:
```
Exception occurred:
  File ".virtualenvs/tract_querier/lib/python3.10/site-packages/sphinx/highlighting.py", line 159, in get_lexer
    lexer = lexer_classes[lang](**opts)
TypeError: 'WMQLLexer' object is not callable
```

raised in a local build with Python 3.10 and Sphinx 8.1.3.

Documentation:
https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_lexer