ENH: Limit the dependencies versions
Limit the dependencies versions:
- Require `NiBabel` lower than 3: the `trackvis` module was deprecated
  in version 3 and definitely removed in version 4:
  https://github.com/nipy/nibabel/releases/tag/4.0.0
- Require `NumPy` lower than 1.20: avoids
  ```
  AttributeError: `np.sctypes` was removed in the NumPy 2.0 release.
  Access dtypes explicitly instead
  ```
  and
  ```
  AttributeError: module 'numpy' has no attribute 'float'.
  `np.float` was a deprecated alias for the builtin `float`.
  To avoid this error in existing code, use `float` by itself.
  Doing this will not modify any behavior and is safe.
  If you specifically wanted the numpy scalar type, use `np.float64` here.
  The aliases was originally deprecated in NumPy 1.20;
  for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

  ```