ENH: Test calling the scripts (#78)
* ENH: Move test files to OSF

Move test files to OSF and refactor the `datasets.py` module:
- Use the new URLs of the test files stored in OSF.
- Add the `b` prefix to the MD5 hashes of the files to match the binary
  string returned by the hash computation method.
- Do not try to encode the byte object with the file contents: some of
  the test files are binary files, and can only be read in binary
  format; trying to read them in text mode raises a `UnicodeDecodeError`
  error when calling `encode('utf-8')` on them, and calling
  `encode('utf-8')` on the bytes read raises a `AttributeError: 'bytes'
  object has no attribute 'encode'` error. Thus, read them in binary
  mode and compute the hash on the returned binary data without trying
  to encode them. Reading the files using chunks is not implemented as
  the files are not that large.
- Remove the unnecessary dependency on `unittest`.

* ENH: Test the CLI scripts

Test the CLI scripts:
- Adapt and transfer the contents of the `test_scripts.py` test script
  to a more modern and compact approach that uses the `pytest`
  `pytest-console-script` plugin and that does not require fiddling
  with the location of the files. This allows to test that the CLI
  scripts are installed appropriately/called using the names defined in
  the `pyproject.toml` `project.scripts` section.
- Split the tests into two different files following the scripts being
  tested: `tract_math` and `tract_querier`.
- Remove the `test_scripts.py` file.

Add the `pytest-console-script` dependency so that the scripts can be
called when executing `pytest`.

Convert the `output.values()` ordered dictionary values to a list prior
to slicing in `decorator.py`. Fixes:
```
"/src/tract_querier/scripts/cli_tract_math.py",
 line 109, in main\n    operations[args.operation]
(\n  File "/src/tract_querier/tract_querier/tract_math/decorator.py",
 line 148, in wrapper\n    process_output(func(*option_and_args))\n
  File "/src/tract_querier/tract_querier/tract_math/decorator.py",
 line 199, in process_output\n
    first_value = output.values()[0]\n
TypeError: \'odict_values\' object is not subscriptable\n')
```

raised locally when running the script tests.

* PERF: Prefer retrieving the next iterator element over slicing

Prefer retrieving the next iterator element over slicing.

* ENH: Use `getfullargspec` instead of deprecated `getargspec`

Use `getfullargspec` instead of deprecated `getargspec` to get the names
and default values of function parameters.

Fixes:
```
inspect. getargspec() is deprecated since Python 3.0,
 use inspect. signature() or inspect. getfullargspec()
```

reported by IDE inspection tool.

---------

Co-authored-by: Demian Wassermann <demian.wassermann@inria.fr>