BUG: Fix miscellaneous errors in scripts (#77)
* BUG: Add the `py` extension to the script filenames

Rename scripts so that their `main` method can be effectively imported
when installing them as Python scripts that can be effectively called
from the command line: add the `py` extension to the script filenames.

Fixes:
```
Traceback (most recent call last):
  File ".virtualenvs/tract_querier/bin/tract_querier", line 5, in <module>
    from scripts.tract_querier import main
ModuleNotFoundError: No module named 'scripts.tract_querier'
Traceback (most recent call last):
  File ".virtualenvs/tract_querier/bin/tract_querier", line 5, in <module>
    from scripts.tract_querier import main
ModuleNotFoundError: No module named 'scripts.tract_querier'
```

raised locally when executing:
```
tract_querier -t "${tractogram_fname}" -a "${wmparc_fname}" -q "${query_fname}" -o "${out_fname}"
```

using some local data.

* BUG: Fix `Mapping` and `Iterables` names import modules

Fix `Mapping` and `Iterables` classes import modules: import them from
`collections.abc` instead of from `collections` as they have been moved
to the former since Python 3.3.

Fixes:
```
Traceback (most recent call last):
  File ".virtualenvs/tract_querier/bin/tract_math", line 8, in <module>
    sys.exit(main())
  File ".virtualenvs/tract_querier/lib/python3.10/site-packages/scripts/tract_math.py", line 33, in main
    from tract_querier.tract_math import operations
  File ".virtualenvs/tract_querier/lib/python3.10/site-packages/tract_querier/tract_math/__init__.py", line 3, in <module>
    from .decorator import tract_math_operation, TractMathWrongArgumentsError
  File ".virtualenvs/tract_querier/lib/python3.10/site-packages/tract_querier/tract_math/decorator.py", line 3, in <module>
    from collections import Mapping, Iterable
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

Documentation:
https://docs.python.org/3.3/library/collections.abc.html

* BUG: Rename scripts: do not use package names to name scripts

Rename scripts: do not use package names to name scripts to avoid
clashes.

If a script has the same name as the package, importing the package or
its submodules within the script may result in Python trying to import
the script itself.

Fixes:
```
Traceback (most recent call last):
  File "/snap/pycharm-professional/443/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/443/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jhlegarreta/src/tract_querier/scripts/tract_querier.py", line 286, in <module>
    main()
  File "/home/jhlegarreta/src/tract_querier/scripts/tract_querier.py", line 94, in main
    if os.path.exists(tract_querier.default_queries_folder):
AttributeError: module 'tract_querier' has no attribute 'default_queries_folder'
```

raised locally when debugging `tract_querier.py`.