ENH: Use `pytest` for testing instead of `nose`
Use `pytest` for testing instead of `nose`: `nose` is no longer
maintained and its successor maintainers `nose2` encourage to use
`pytest` as it as a bigger team of maintainers and a larger community of
users.

Avoids errors that stem from using `nose` as the testing tool:
```
AttributeError: module 'collections' has no attribute 'Callable'
```

raised for example in:
https://github.com/demianw/tract_querier/actions/runs/12168541455/job/33939552914#step:6:37

Documentation:
https://github.com/nose-devs/nose2
https://docs.pytest.org/en/latest/