ENH: Require a more recent version of `NumPy`
Require a more recent version of `NumPy`: require any version greater or
equal to 1.19.5 but lower than 2.0.0. `NumPy` 1.19.5 was the first
release supporting Python 3.9.

Fixes:
```
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

raised for example at:
https://github.com/demianw/tract_querier/actions/runs/12145326696/job/33866697673#step:5:806